server:
  port: 8080
  servlet:
    context-path: /identity_service
  tomcat:
    connection-timeout: 3360s
spring:
  datasource:
    url: "jdbc:mysql://localhost:3300/identity_service"
    username: root
    password: 1234
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true

jwt:
  signerKey: "Z3mgGYMYw4RDo1fxTPtTK/topu9tMO4diopz9x+h8rUzx3f5veaywpHIdFJaV8fm"
  valid-duration: 360 # in second
  refreshable-duration: 3600 # in seconds

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
