server:
  port: 8080
  servlet:
    context-path: /identity_service


spring:
  datasource:
    url: "jdbc:mysql://localhost:3300/identity_service"
    username: root
    password: 1234
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
